### ISSUE TITLE
Issues regarding Jenkins startup on Openshift

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#170] opened 2019-10-24 23:24 UTC
Having some issues with CNIs and mounting volumes while running the jenkins-operator on Openshift
```
0s          Warning   FailedCreatePodSandBox   pod/jenkins-example   Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "39917a7a343b5b77cbaa88ae2e80de320e0733d464a250
3f06ce3502db1db714" network for pod "jenkins-example": NetworkPlugin cni failed to set up pod "jenkins-example_jenkins-sync-test" network: failed to Statfs "/proc/128763/ns/net": no such file or directory      
0s          Normal    Scheduled                pod/jenkins-example   Successfully assigned jenkins-sync-test/jenkins-example to shiftmaster                                                                       
0s          Warning   FailedMount              pod/jenkins-example   Unable to mount volumes for pod "jenkins-example_jenkins-sync-test(a9d02519-f6b3-11e9-af25-001a4a000264)": timeout expired waiting for volumes
 to attach or mount for pod "jenkins-sync-test"/"jenkins-example". list of unmounted volumes=[jenkins-home scripts init-configuration operator-credentials jenkins-operator-example-token-m88rs]. list of unattache
d volumes=[jenkins-home scripts init-configuration operator-credentials jenkins-operator-example-token-m88rs] 
```

Kubelet logs
```
Oct 24 19:22:37 shiftmaster atomic-openshift-node[61795]: I1024 19:22:37.055680   61795 kubelet.go:1830] SyncLoop (REMOVE, "api"): "jenkins-example_jenkins-sync-test(27891ff8-f6b5-11e9-af25-001a4a000264)"                                                                   
Oct 24 19:22:37 shiftmaster atomic-openshift-node[61795]: I1024 19:22:37.055792   61795 kubelet_pods.go:1082] Killing unwanted pod "jenkins-example"                                                                                                                           
Oct 24 19:22:37 shiftmaster atomic-openshift-node[61795]: W1024 19:22:37.061914   61795 cni.go:243] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "4ba96567483f2161e6e969ce2dcb787f8671eeb5151067186e1566799a451d7a"
```

**Comment by pawelprazak** [comment] 2019-10-25 07:34
Hmm, I'm not sure what the cause is from the provided info.

At first glance it looks like a Kubernetes misconfiguration, a CNI provider issue, a CRI provider issue or some kind of security feature, like PSP.

Do you have any more information?

**Comment by pawelprazak** [comment] 2019-11-07 12:28
FYI: As a part of #190 we'll be attempting to reproduce those issues and then address them

**Comment by pawelprazak** [comment] 2019-11-15 13:08
closing in favour of #190

**Closed by pawelprazak** 2019-11-15 13:08 UTC
Labels: question
