### ISSUE TITLE
seedJobAgentImage parameter does not work

### ISSUE THREAD

**Issue by tomvopat** [jenkinsci/kubernetes-operator#768] opened 2022-09-20 09:51 UTC
**Describe the bug**
If the agent image is specified using seedJobAgentImage, it doesn't come in use.

**To Reproduce**
Set seedJobAgentImage in values.yaml file and check the job container image once running

**Additional information**
Weird is when I specified:
`<private_repository>/jenkins/jenkins/inbound-agent:4.11-1-jdk11`

Then containers were created with
`jenkins/inbound-agent:4.11-1-jdk11` (private repository is missing)

Kubernetes version: v1.23.3
Jenkins Operator version: 0.7.1

**Comment by Harguer** [comment] 2022-09-20 16:30
Hi @tomvopat , I think the latest tag (v0.71) does not have that change, try with image tag [94b1473](https://hub.docker.com/layers/virtuslab/jenkins-operator/94b1473/images/sha256-b9393e0cb0aeb43c89dae55b940bebedb656a064ef16c7c87140eb96d33930c6?context=explore)

I'm not sure when this feature and another like the plugin versioning will be available in the latest version, but in the meantime  I'm using 94b1473 and it is working fine.

```
$ k get deployment -o yaml jenkins-operator | grep -i 94b1473
        image: virtuslab/jenkins-operator:94b1473
$
```

**Comment by Harguer** [comment] 2022-09-20 16:56
Also seems this is duplicate of https://github.com/jenkinsci/kubernetes-operator/issues/761 ?

**Comment by tomvopat** [comment] 2022-09-23 11:15
Hi @Harguer, thanks for the explanation! I didn't think of checking whether the change made it to the release as long as it is mentioned in the release notes though.

Yeah, it's a duplicate.

**Closed** 2022-09-23 11:16 UTC
Labels: bug
