### ISSUE TITLE
Jenkins loses all setting and data after restart

### ISSUE THREAD

**Issue by narsinallamilli** [jenkinsci/kubernetes-operator#1036] opened 2024-07-18 05:52 UTC
**Describe the bug**
Jenkins console doesn't retain settings after restart. Below screenshot show an instance where I update the plugins but after restart the updates don't appear.

**To Reproduce**
Install jenkins-operatator through helm with pvc reference set on EKS.

**Additional information**

Kubernetes version:
jenkins-operator - v0.81
kubeclt version
Client Version: v1.30.0-eks-036c24b
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0

`
###############################################################################################################
nnallam@nnallam-897K8VQI:~/selenium-terraform-aws-kubernetes/terraform3$ kubectl get pvc -n jenkins
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
jenkins-backup   Bound    pvc-ee113299-d70d-4690-98c5-edf4b252446f   5Gi        RWO            efs-sc         <unset>                 27m
###############################################################################################################
nnallam@nnallam-897K8VQI:~/selenium-terraform-aws-kubernetes/terraform3$ kubectl get all -n jenkins
NAME                                           READY   STATUS    RESTARTS   AGE
pod/jenkins-jenkins                            2/2     Running   0          18m
pod/jenkins-jenkins-operator-97f687d8c-4dn6r   1/1     Running   0          18m

NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/jenkins-operator-http-jenkins    ClusterIP   xxx.xx.173.138   <none>        8080/TCP         18m
service/jenkins-operator-slave-jenkins   ClusterIP   xxx.xx.115.164   <none>        50000/TCP        18m
service/jenkins-service                  NodePort    xxx.xx.90.141    <none>        8080:32000/TCP   19h

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins-jenkins-operator   1/1     1            1           18m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-jenkins-operator-97f687d8c   1         1         1       18m

################################################################################################################
nnallam@nnallam-897K8VQI:~/selenium-terraform-aws-kubernetes/terraform3$ kubectl describe pod jenkins-jenkins -n jenkins
Name:             jenkins-jenkins
Namespace:        jenkins
Priority:         0
Service Account:  jenkins-operator-jenkins
Node:             ip-10-0-42-236.ec2.internal/10.0.42.236
Start Time:       Thu, 18 Jul 2024 10:39:29 +0530
Labels:           app=jenkins-operator
                  jenkins-cr=jenkins
Annotations:      <none>
Status:           Running
IP:               10.0.32.30
IPs:
  IP:           10.0.32.30
Controlled By:  Jenkins/jenkins
Containers:
  jenkins-master:
    Container ID:  containerd://eecbc6a7f9e1bde9113a8a5a0af17c05b9344943bb8341ac5c1752591a8409a3
    Image:         jenkins/jenkins:2.452.2-lts
    Image ID:      docker.io/jenkins/jenkins@sha256:b40d2dc5a664b52dd3e30fad8f2bd3f82bd0ef3365d656a1f39769e60717c0b6
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      bash
      -c
      /var/jenkins/scripts/init.sh && exec /usr/bin/tini -s -- /usr/local/bin/jenkins.sh
    State:          Running
      Started:      Thu, 18 Jul 2024 10:39:30 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  3Gi
    Requests:
      cpu:      250m
      memory:   500Mi
    Liveness:   http-get http://:http/login delay=100s timeout=8s period=10s #success=1 #failure=20
    Readiness:  http-get http://:http/login delay=120s timeout=8s period=10s #success=1 #failure=60
    Environment:
      COPY_REFERENCE_FILE_LOG:  /var/lib/jenkins/copy_reference_file.log
      JAVA_OPTS:                -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
      JENKINS_HOME:             /var/lib/jenkins
    Mounts:
      /var/jenkins/init-configuration from init-configuration (ro)
      /var/jenkins/operator-credentials from operator-credentials (ro)
      /var/jenkins/scripts from scripts (ro)
      /var/lib/jenkins from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8694v (ro)
  backup:
    Container ID:   containerd://c8967d03854afe78b1328c63b36904f06c78c8a3196281b4274ae239f8e9bc2a
    Image:          quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.1
    Image ID:       quay.io/jenkins-kubernetes-operator/backup-pvc@sha256:7709743a2536cf5bc7fb2407e796bb78241f4512a1703e483b2bdd82e27f56d0
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 18 Jul 2024 10:39:30 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     100m
      memory:  500Mi
    Environment:
      BACKUP_DIR:    /backup
      JENKINS_HOME:  /jenkins-home
      BACKUP_COUNT:  3
    Mounts:
      /backup from backup (rw)
      /jenkins-home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8694v (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       True
  ContainersReady             True
  PodScheduled                True
Volumes:
  jenkins-home:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkins-operator-scripts-jenkins
    Optional:  false
  init-configuration:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkins-operator-init-configuration-jenkins
    Optional:  false
  operator-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenkins-operator-credentials-jenkins
    Optional:    false
  backup:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jenkins-backup
    ReadOnly:   false
  kube-api-access-8694v:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  19m   default-scheduler  Successfully assigned jenkins/jenkins-jenkins to ip-10-0-42-236.ec2.internal
  Normal  Pulling    19m   kubelet            Pulling image "jenkins/jenkins:2.452.2-lts"
  Normal  Pulled     19m   kubelet            Successfully pulled image "jenkins/jenkins:2.452.2-lts" in 134ms (134ms including waiting). Image size: 282486292 bytes.
  Normal  Created    19m   kubelet            Created container jenkins-master
  Normal  Started    19m   kubelet            Started container jenkins-master
  Normal  Pulling    19m   kubelet            Pulling image "quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.1"
  Normal  Pulled     19m   kubelet            Successfully pulled image "quay.io/jenkins-kubernetes-operator/backup-pvc:v0.4.1" in 99ms (99ms including waiting). Image size: 30675648 bytes.
  Normal  Created    19m   kubelet            Created container backup
  Normal  Started    19m   kubelet            Started container backup
#############################################################################################################################################################################################
nnallam@nnallam-897K8VQI:~/selenium-terraform-aws-kubernetes/terraform3$ kubectl describe deployment jenkins-jenkins-operator -n jenkins
Name:                   jenkins-jenkins-operator
Namespace:              jenkins
CreationTimestamp:      Thu, 18 Jul 2024 10:39:09 +0530
Labels:                 app.kubernetes.io/instance=jenkins
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=jenkins-operator
                        app.kubernetes.io/version=0.8.1
                        helm.sh/chart=jenkins-operator-0.8.1
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: jenkins
                        meta.helm.sh/release-namespace: jenkins
Selector:               app.kubernetes.io/instance=jenkins,app.kubernetes.io/name=jenkins-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=jenkins
                    app.kubernetes.io/name=jenkins-operator
  Service Account:  jenkins-operator
  Containers:
   jenkins-operator:
    Image:      quay.io/jenkins-kubernetes-operator/operator:v0.8.1
    Port:       80/TCP
    Host Port:  0/TCP
    Command:
      /manager
    Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      WATCH_NAMESPACE:  jenkins
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    jenkins-operator
    Mounts:             <none>
  Volumes:              <none>
  Node-Selectors:       <none>
  Tolerations:          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   jenkins-jenkins-operator-97f687d8c (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  22m   deployment-controller  Scaled up replica set jenkins-jenkins-operator-97f687d8c to 1
####################################################################################################################################
`

Add error logs about the problem here (operator logs and Kubernetes events).
update plugins
![1](https://github.com/user-attachments/assets/ac6a94eb-0c55-46c4-8934-cd3bca1d2c8f)

after plugins updated before restart
![2](https://github.com/user-attachments/assets/22db0bff-948d-466b-97cb-dcb59cf1c896)

after restart, see plugins not udpated
![3](https://github.com/user-attachments/assets/afab5efa-2e48-4884-90c5-75d9d51c93ec)

**Comment by brokenpip3** [comment] 2024-07-21 09:23
> Jenkins console doesn't retain settings after restart

This is the expected behavior, if you want to keep your plugins version and settings you need to put them as code, this is the flow of this operator, everything must be declared in the jenkins crd and any configmap or secret, check the documentation, for instance: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customizing-jenkins/

Feel free to open other bugs but I'm going to close this since it's the expected behavior

**Closed by brokenpip3** 2024-07-21 09:23 UTC
Labels: bug

**Comment by Shashankft9** [comment] 2025-01-23 12:04
@brokenpip3 is there no way to persist the plugins, pipelines etc when the jenkins master pod restarts? If there is an option to add plugins from the UI, isnt asking the user to make the change in the CR an anti pattern? 
I have only recently started exploring jenkins operator, so I am not quite sure on how it works, but would it be possible to somehow take backup of everything in my jenkins server and then restore it when the pod starts?

I had a look at this as well: https://github.com/jenkinsci/kubernetes-operator/issues/104#issuecomment-554289768, which mentions that jenkins backup-restore utility only restore job history, but I'd think a pod in a kubernetes cluster can restart several times - could be node issue, or cluster level issue, shouldnt the data be persisted anywhere? Even if I add all the plugins in the CR, how do i ensure the pipelines, creds are restored when jenkins restarts?

I would appreciate if you can share some examples of jcasc that does the same thing?
