### ISSUE TITLE
seed-job-agent container cannot clone the kubernetes-operator repository

### ISSUE THREAD

**Issue by AaronJaegerVA** [jenkinsci/kubernetes-operator#528] opened 2021-03-11 14:21 UTC
**Describe the bug**

The seed-job-agent container cannot clone the kubernetes-operator repository because it cannot resolve the host github.com; however, testing resolution in the container for github.com seems to work without issue.

```
bash-5.0$ nslookup github.com
Server:         10.43.0.10
Address:        10.43.0.10:53
Non-authoritative answer:
Name:   github.com
Address: 192.30.255.112
Non-authoritative answer:
. 
.
.
bash-5.0$ git clone https://github.com/jenkinsci/kubernetes-operator.git/
Cloning into 'kubernetes-operator'...
fatal: unable to access 'https://github.com/jenkinsci/kubernetes-operator.git/': Could not resolve host: github.com
```

**Additional information**

Kubernetes version: 1.20
Jenkins Operator version: 0.6.2

**Comment by AaronJaegerVA** [comment] 2021-03-11 14:42
I know from past experience that alpine behaves strangely when it comes to DNS resolution so I decided to edit the seed-job-agent deployment to use a different `jenkins/inbound-agent` image. I switched from `jenkins/inbound-agent:alpine` to `jenkins/inbound-agent:latest-jdk11` and all is well now.

**Comment by rafabene** [comment] 2021-07-21 19:31
I'm facing the same issue. Is there any workaround?

**Comment by rafabene** [comment] 2021-07-21 20:37
The following command updates the seed-job-agent-master image.

`kubectl patch deployment seed-job-agent-master -p '{"spec":{"template":{"spec":{"containers":[{"name":"jnlp","image":"jenkins/inbound-agent:latest-jdk11"}]}}}}'`

**Comment by Sig00rd** [comment] 2021-07-22 15:10
Thank you for your input. I've managed to reproduce the problem on minikube with latest version of the Operator. It seems to be related to this issue with alpine image: https://github.com/kubernetes/minikube/issues/10830.
inbound-agent:4.9-1 seems all right, so I'll make a quick PR with the image version bump.

**Comment by Sig00rd** [comment] 2021-07-23 10:27
With PR bumping the agent image version merged, using the next Operator nightly build (the one scheduled for tomorrow) should fix the problem, I'll update here once I verify it's working correctly and until then, ```patch```ing seedjob agent deployment as @rafabene suggested should help

**Comment by Sig00rd** [comment] 2021-07-26 13:21
I've just tested it, using Operator's nightly build solves the problem. Thank you for reporting this problem and keeping this issue alive!

**Closed by Sig00rd** 2021-07-26 13:21 UTC
Labels: bug
