### ISSUE TITLE
Migrate Jenkins instance from Pod to Deployment

### ISSUE THREAD

**Issue by antoniaklja** [jenkinsci/kubernetes-operator#497] opened 2021-01-20 16:37 UTC
We should use Deployment instead of Pod. This change will unlock more abilities and gives us more control over the Jenkins.

**Comment by Chris-Carmichael** [comment] 2021-08-23 00:38
I'm running into a problem with the active-directory plugin not honoring the site.  Jenkins can't connect to every domain controller on the network, which causes auth problems.  A simple addition to `/etc/hosts` would solve the problem, but I'm not able to do it with the current pattern.  A deployment would solve that for me also.

**Comment by brokenpip3** [comment] 2023-03-07 22:17
close as duplicate of https://github.com/jenkinsci/kubernetes-operator/issues/195

**Closed by brokenpip3** 2023-03-07 22:17 UTC
Labels: enhancement
