### ISSUE TITLE
Unable to deploy since a few days ago

### ISSUE THREAD

**Issue by yoshi314** [jenkinsci/kubernetes-operator#136] opened 2019-10-10 09:53 UTC
I am seeing something along these lines in logs : 

```
jenkins-example jenkins-master 2019-10-10 09:46:32.466+0000 [id=29]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git client plugin v2.9.0 (git-client)
jenkins-example jenkins-master java.io.IOException: Jenkins Git client plugin version 2.9.0 failed to load.
jenkins-example jenkins-master  - Configuration as Code Plugin version 1.29 is older than required. To fix, install version 1.30 or later.
```

This is with the specs in the documentation for 0.2.0 and i also tried 0.2.2

I did not specify git plugin version at all, and i doubt i can control configuration-as-code version.

**Comment by jakalkhalili** [comment] 2019-10-10 10:15
Hi
Look at @tomaszsek https://github.com/jenkinsci/kubernetes-operator/issues/126 first comment. This should fix this issue. In the next release, we will fix this by default.

**Comment by pawelprazak** [comment] 2019-10-11 12:48
closing as duplicate of #126

**Closed by pawelprazak** 2019-10-11 12:48 UTC
Labels: duplicate
