### ISSUE TITLE
trouble with persistence of build-numbers with backup/restore

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#210] opened 2019-11-25 10:06 UTC
We have backup/restore integrated so whenever a fresh instance of jenkins is created we have the history of our jobs available.

Unfortunatly we can't trigger new builds though as we are running into exceptions when clicking the build buttons/links.  We always first have to go to manage jenkins, reload configuration from disk, in order for jenkins to have proper build numbers in place for the build/run actions.

This ist the exception, before running "reload from disk":

```
Nov 25, 2019 9:00:08 AM SEVERE hudson.model.Executor run
Executor #-1 for master: Unexpected executor death
java.lang.IllegalStateException: JENKINS-23152: /var/jenkins/home/jobs/xxxx/jobs/yyyy/branches/master/builds/3 already existed; will not overwrite with xxxx/yyyy/master #3
	at hudson.model.RunMap.put(RunMap.java:189)
	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:182)
Caused: java.lang.Error
	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:190)
	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:511)
	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:321)
	at hudson.model.Executor$1.call(Executor.java:365)
	at hudson.model.Executor$1.call(Executor.java:347)
	at hudson.model.Queue._withLock(Queue.java:1438)
	at hudson.model.Queue.withLock(Queue.java:1299)
	at hudson.model.Executor.run(Executor.java:347)
```

Is this a general problem or just something messed up on our side?

**Comment by tomaszsek** [comment] 2019-11-25 19:36
Hi @pniederlag,

After the restore the operator calls the `Jenkins.instance.reload()` https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/configuration/backuprestore/backuprestore.go#L154 which reloads data from the disk. Unfortunately this is not working with the Multibranch jobs. There is no solution implemented in the operator but you can check the workarounds in #104.

Cheers

**Comment by pawelprazak** [comment] 2019-11-26 09:11
Yes, I've spent 3 week trying to find all the workarounds to make multi-brunch work with job dls and backups...

**Comment by pawelprazak** [comment] 2019-11-26 10:07
This is a funny bug actually, if you click run enough times it starts to work ;)
There are more details in the #104

**Comment by pawelprazak** [comment] 2019-11-26 10:24
Closing as a duplicate of #104

**Closed by pawelprazak** 2019-11-26 10:24 UTC
Labels: bug
