### ISSUE TITLE
Cannot handle configuration string over 65535 characters long

### ISSUE THREAD

**Issue by Nuru** [jenkinsci/kubernetes-operator#328] opened 2020-04-14 02:20 UTC
Using operator v0.4.0 with 
I tried to set the `cssText` field for [`simple-theme-plugin`](https://github.com/jenkinsci/simple-theme-plugin) via [Configuration as Code](https://github.com/jenkinsci/configuration-as-code-plugin), but it choked because the field was too big. I don't know if this is an error in the `kubernetes-operator` or the `configuration-as-code-plugin`, but it is a Groovy script error, so I am guessing the bug report belongs here.

```
 controller-jenkins      groovy/groovy.go:57     user-casc Source 'jenkins-plugins-configuration' Name 'simple-th
eme-plugin-configuration.yaml' groovy script execution failed, logs :
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 2: String too long. The given string is 131529 Unicode code units long, but only a maximum of 65535 is allowed.
 @ line 2, column 14.
   def config = '''
                ^
```

**Comment by tomaszsek** [comment] 2020-04-14 07:51
@Nuru,

I think the problem is on the operator side. I have to do some research on how we can solve it.

Cheers

**Comment by waveywaves** [comment] 2020-04-15 12:44
@Nuru What is the cssText that you were passing ?

**Comment by waveywaves** [comment] 2020-04-15 12:50
@tomaszsek in `/pkg/controller/jenkins/configuration/user/casc/caac.go` the CASCscript is created using `applyConfigurationAsCodeGroovyScriptFmt`.

```
const applyConfigurationAsCodeGroovyScriptFmt = `
def config = '''
%s
'''
def stream = new ByteArrayInputStream(config.getBytes('UTF-8'))

def source = new io.jenkins.plugins.casc.yaml.YamlSource(stream, io.jenkins.plugins.casc.yaml.YamlSource.READ_FROM_INPUTSTREAM)
io.jenkins.plugins.casc.ConfigurationAsCode.get().configureWith(source)
`
```
The error is happening at `stream` where the configuration seems to have gotten too big. 
@Nuru Can you help with the `cssText` argument you are passing for this ? It would be easier to help you out

**Comment by Nuru** [comment] 2020-04-15 18:44
@waveywaves The exact contents of the `cssText` field is not important, only its length. You can use, for example, http://afonsof.com/jenkins-material-theme/dist/material-light.css

**Comment by tomaszsek** [comment] 2020-06-19 14:31
Hi @Nuru,

The fix is merged to the master and will be added in the next release.

Cheers

**Comment by sboardwell** [comment] 2020-09-10 15:47
Hi @tomaszsek, could you tell me when the next release is going to be please?

**Comment by tomaszsek** [comment] 2021-01-18 22:18
Fixed in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.5.0

**Closed by tomaszsek** 2021-01-18 22:18 UTC
Labels: bug
