### ISSUE TITLE
Seed Job or normal job ?

### ISSUE THREAD

**Issue by shinji62** [jenkinsci/kubernetes-operator#75] opened 2019-08-20 02:36 UTC
Hi, 
First I am not sure about the difference with the seed-job or non seed-job. 
But what I would like to know is quite simple. 

We may provide for each of our team a CRD (jenkins master) where the will configure their jobs, the problem with the seed job is that jenkins try to run it when the master restart which we don't really want.  But the good things is the seed job could be configure from Repos which mean we don't need to define the job in the Yaml file but just the repository.

So we are thinking about non seed job but in this case using the `configmap` could be an issue as the limit for a configmap is `1MB` which could be quickly filled when we configure multiple plugin and multiple job. 

One improvement could be to create one configmap for each non-seed job like the `grafana` k8sis doing with the dashboard, each dashboard is a configmap and this solution scale. Or decide which job should run or not with the seed-job.

**Comment by tomaszsek** [comment] 2019-08-20 08:12
Hi @shinji62,

First I really recommend use seed-jobs and define all yours jobs in repository, but If you want you can create it via groovy scripts or Configuration as Code plugin. In the future release `v0.2.0` you will be able to configure multiple config maps https://github.com/jenkinsci/kubernetes-operator/issues/28#issuecomment-500359852 and that will solve your issue.

Cheers

**Comment by shinji62** [comment] 2019-08-21 00:53
@tomaszsek I prefer the seed-job, but can we avoid to make the deployed job to be run ... 
For example we have nightly build and so and we don't want those job to start everytime the seed-job is running. I guess this could be just a small parameters in the CRD.

**Comment by jakalkhalili** [comment] 2019-09-26 11:46
Hi @shinji62 
If the problem is solved, please close the issue. 

Thanks.

**Closed** 2019-10-17 14:09 UTC
