### ISSUE TITLE
The yaml to deploy jenkins operators "CRD" has the wrong API Version

### ISSUE THREAD

**Issue by fl0wm0ti0n** [jenkinsci/kubernetes-operator#682] opened 2021-12-12 20:21 UTC
**Describe the bug**
The yaml to deploy jenkins operators "customresourcedefinitions" has the wrong API Version. If i try to run it via "apply -f url"

file: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml

error: unable to recognize "https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

If i search for the Versions and Apis via "kubectl api-resources" and "kubectl api-versions" there is only following version:
customresourcedefinitions apiextensions.k8s.io/v1

if i change the Api version in the yaml to "apiextensions.k8s.io/v1" i get the following error:

apply -f jenkins-crd.yaml
error: error validating "jenkins-crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**To Reproduce**
kubectl apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml

**Additional information**
Furthermore: the Url on the Tutorial (here: https://www.jenkins.io/doc/book/installing/kubernetes/#install-jenkins-operator) doesnt exist.
https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins_v1alpha2_jenkins_crd.yaml

Kubernetes version: latest microk8s ->
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:07:39Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:03:17Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Jenkins Operator version: latest

**Comment by fl0wm0ti0n** [comment] 2021-12-12 20:48
just realized that, if i follow the rules here ....
 https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/

instead of here ...  https://www.jenkins.io/doc/book/installing/kubernetes/#install-jenkins-operator

... than it works. So the solution will be, to update the second tutorialpage

**Comment by fl0wm0ti0n** [comment] 2021-12-12 22:00
maybe its wrong here but, the main jenkins git has no issue-tab...and its relatet to this issue...

if i managed to run jenkins-operator like in my second post. and i want to run the jenkins installation via the Kind "jenkins" see example code and Url, then i got following error... maybe there is a operator error or also a old Wiki-entry... i dont finy the correkt yaml fopr jenkins over operator...

$ kubelctl create -f jenkins.yaml -n jenkins
error: error validating "jenkins.yaml": error validating data: [ValidationError(Jenkins.spec.master): missing required field "disableCSRFProtection" in io.jenkins.v1alpha2.Jenkins.spec.master, ValidationError(Jenkins.spec): missing required field "jenkinsAPISettings" in io.jenkins.v1alpha2.Jenkins.spec]; if you choose to ignore these errors, turn validation off with --validate=false


Followed this:
https://www.jenkins.io/doc/book/installing/kubernetes/#deploy-jenkins-2

With this Example Code:
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts-jdk11
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git

**Comment by Sig00rd** [comment] 2021-12-13 10:28
Hello @fl0wm0ti0n , thanks for pointing that out.
If I understand you correctly, everything works fine when you're following Jenkins Operator documentation, but deploying Jenkins breaks when using documentation on jenkins.io page, which is lacking and outdated. 

I'll issue a PR to jenkins-infra to fix that later but generally, for working with Jenkins Operator, please use Jenkins Operator documentation, which you can find [under the link you've posted](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/) because it is the most up-to-date. 

I'm closing this issue since it's not a bug and it's not related to this repository, but if you encounter problems setting up or using Jenkins Operator while following its documentation, feel free to open up another issue. Thanks!

**Closed by Sig00rd** 2021-12-13 10:28 UTC
Labels: bug

**Comment by Sig00rd** [comment] 2021-12-14 10:01
Jenkins maintainers have already merged my PR removing the outdated docs you mentinoed (https://github.com/jenkins-infra/jenkins.io/pull/4766). Again, thanks for pointing that out!
