### ISSUE TITLE
Please add support for affinity in Jenkins/operator pod templates

### ISSUE THREAD

**Issue by dgilmanTORQATA** [jenkinsci/kubernetes-operator#595] opened 2021-07-08 14:00 UTC
**Describe the solution you'd like**
The CRD supports passing `nodeSelector` down to the pods for Jenkins and the operator but it does not whitelist the `affinity` object. Please consider supporting `affinity` on pods.

**Describe alternatives you've considered**
I was able to hack around it with a `nodeSelector` that worked but it would be best for my use case to support the whole `affinity` as that would let the pod be more compliant with how stuff is done elsewhere in the cluster.

**Comment by KorusMateusz** [comment] 2021-07-09 09:30
Hello, we are currently working on a new API implementation. In the new API we're using a Deployment for Jenkins instance so that will allow you to pass the `affinity` field

**Comment by KorusMateusz** [comment] 2021-07-09 09:38
Closing as a duplicate of #538

**Closed by KorusMateusz** 2021-07-09 09:38 UTC
Labels: enhancement
