### ISSUE TITLE
errors Reconcile loop failed 10 times with the same error, giving up: couldn't generate API token: 403	

### ISSUE THREAD

**Issue by riqio** [jenkinsci/kubernetes-operator#305] opened 2020-03-27 17:48 UTC
Trying to deploy the basic jenkins operator on local docker instance and i keep see the following error message 

7T17:43:21.761Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:171	Reconcile loop failed: couldn't generate API token: 403	{"cr": "example"}
2020-03-27T17:43:22.687Z	INFO	controller-jenkins	base/reconcile.go:869	Generating Jenkins API token for operator	{"cr": "example"}
2020-03-27T17:43:22.969Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:171	Reconcile loop failed: couldn't generate API token: 403	{"cr": "example"}
2020-03-27T17:43:23.902Z	INFO	controller-jenkins	base/reconcile.go:869	Generating Jenkins API token for operator	{"cr": "example"}
2020-03-27T17:43:24.177Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:171	Reconcile loop failed: couldn't generate API token: 403	{"cr": "example"}
2020-03-27T17:43:25.087Z	INFO	controller-jenkins	base/reconcile.go:869	Generating Jenkins API token for operator	{"cr": "example"}
2020-03-27T17:43:25.368Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:171	Reconcile loop failed: couldn't generate API token: 403	{"cr": "example"}
2020-03-27T17:43:26.713Z	INFO	controller-jenkins	base/reconcile.go:869	Generating Jenkins API token for operator	{"cr": "example"}
2020-03-27T17:43:26.994Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:171	Reconcile loop failed: couldn't generate API token: 403	{"cr": "example"}
2020-03-27T17:43:29.643Z	INFO	controller-jenkins	base/reconcile.go:869	Generating Jenkins API token for operator	{"cr": "example"}
2020-03-27T17:43:29.937Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:152	Reconcile loop failed 10 times with the same error, giving up: couldn't generate API token: 403	{"cr": "example"}

It is not able to pull seed jobs 

I did reset my k8s on docker and still encountering this issue 

Thanks
Venkata

**Comment by riqio** [comment] 2020-03-27 17:49
I am using the following to deploy my pod 
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git

**Comment by tomaszsek** [comment] 2020-03-27 20:17
Please look at #303. As a workaround, you can set `2.204.5` Jenkins docker tag. It will be fixed in `0.4.0`.

**Comment by tomaszsek** [comment] 2020-03-30 09:48
Closing as duplicate of #303

**Closed by tomaszsek** 2020-03-30 09:48 UTC
Labels: bug, duplicate
